In [1]:
import torch
import numpy as np

In [2]:
t1=torch.tensor([[1,2],[3,4]],dtype=torch.float32)
t2=torch.tensor([[9,8],[7,6]],dtype=torch.float32)

In [3]:
#element wise operations
t1+t2 

tensor([[10., 10.],
        [10., 10.]])

In [4]:
t1+2

tensor([[3., 4.],
        [5., 6.]])

In [5]:
t1*2

tensor([[2., 4.],
        [6., 8.]])

In [7]:
t1.mul(2)    #add,sub,mul,div

tensor([[2., 4.],
        [6., 8.]])

In [8]:
np.broadcast_to(2,t1.shape)

array([[2, 2],
       [2, 2]])

In [9]:
t1+torch.tensor(np.broadcast_to(2,t1.shape),dtype=torch.float32)    #which is how t1+2 works that is making the scalar same shape as t1 and proceeding with operation

tensor([[3., 4.],
        [5., 6.]])

In [10]:
t1=torch.tensor([[1,1],[1,1]],dtype=torch.float32)
t2=torch.tensor([[2,4]],dtype=torch.float32)

In [11]:
t1+t2    #happens with help of broadcasting operation

tensor([[3., 5.],
        [3., 5.]])

In [12]:
t=torch.tensor([[0,1,0],[2,0,2],[0,3,0]],dtype=torch.float32)

In [13]:
t.sum()

tensor(8.)

In [14]:
t.sum().numel()

1

In [15]:
t.sum().numel()<t.numel()

True

In [16]:
t=torch.tensor([[1,1,1,1],[2,2,2,2],[3,3,3,3]],dtype=torch.float32)

In [19]:
t.sum(dim=0)  #first axis arrays

tensor([6., 6., 6., 6.])

In [20]:
t.sum(dim=1)  #second axis numbers

tensor([ 4.,  8., 12.])

In [21]:
t=torch.tensor([[1,0,0,2],[0,3,3,0],[4,0,0,5]],dtype=torch.float32)

In [22]:
t.max()

tensor(5.)

In [23]:
t.argmax()  #index of max value from flatten tenson

tensor(11)

In [24]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [25]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [26]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [27]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [28]:
t.argmax(dim=1)

tensor([3, 1, 3])

In [29]:
t.mean()

tensor(1.5000)

In [30]:
t.mean().item()

1.5

In [31]:
t.mean(dim=0).tolist()

[1.6666666269302368, 1.0, 1.0, 2.3333332538604736]

In [32]:
t.mean(dim=0).numpy()

array([1.6666666, 1.       , 1.       , 2.3333333], dtype=float32)