In [13]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.9.0+cu102


In [4]:
torch.cuda.is_available()

True

In [5]:
torch.version.cuda

'10.2'

In [6]:
t=torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [7]:
t=t.cuda()

In [8]:
t

tensor([1, 2, 3], device='cuda:0')

In [1]:
dd=[[1,2,3,],[4,5,6],[7,8,9]]

In [4]:
t=torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
t.shape

torch.Size([3, 3])

In [6]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [7]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [9]:
t=torch.Tensor()
type(t)

torch.Tensor

In [10]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [11]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [20]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [21]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [22]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [23]:
torch.rand(2,2)

tensor([[0.4350, 0.4493],
        [0.7520, 0.8140]])

In [44]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [45]:
t1=torch.Tensor(data)

In [46]:
t2=torch.tensor(data)

In [47]:
t3=torch.as_tensor(data)

In [48]:
t4=torch.from_numpy(data)

In [49]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [50]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [51]:
torch.get_default_dtype()

torch.float32

In [52]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3], dtype=torch.int32)

In [53]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [54]:
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [55]:
data[0]=0
data[1]=0
data[2]=0

In [56]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
